[colors.primary]
background = "0x000000"
# foreground = "0xafc2c2"

# [colors.cursor]
# cursor = "0xffffff"
# text = "0x000000"

# [colors.selection]
# background = "0x7cbeff"
# text = "0x000000"

[colors.normal]
black   = "0x000000"
red     = "0xff2f2f"
green   = "0x549a6f"
yellow  = "0xccac00"
blue    = "0x0099cc"
magenta = "0xcc68c8"
cyan    = "0x79c4cc"
white   = "0xbccccc"

[colors.bright]
# black   = "0x000000"
# red     = "0xff2f2f"
# green   = "0x549a6f"
# yellow  = "0xccac00"
# blue    = "0x0099cc"
# magenta = "0xcc68c8"
# cyan    = "0x79c4cc"
# white   = "0xbccccc"
