[general]
import = [
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/colors.toml",
  "/usr/lib/node_modules/alacritty-themes/themes/Dracula.toml"
]
live_config_reload = true
ipc_socket = true

[font]
size = 10

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "FiraCode Nerd Font Mono"

[font.offset]
x = 0
y = 0

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
# position = "None"
opacity = 0.86
blur = false
dynamic_padding = true
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true
decorations_theme_variant = "None"

[window.class]
  instance = "Alacritty"
  general = "Alacritty"

  [window.dimensions]
  columns = 82
  lines = 24

  [window.padding]
  x = 12
  y = 12

[cursor]
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.15

  [cursor.style]
  shape = "Block"
  blinking = "On"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false

  [hints.enabled.mouse]
  enabled = true

  [hints.enabled.binding]
  key = "U"
  mods = "Control|Shift"

[scrolling]
history = 10_000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = false

# [[hints.enabled]]
# command         = "xdg-open"
# hyperlinks      = true
# post_processing = true
# persist         = false
# mouse.enabled   = true
# binding         = { key = "U", mods = "Control|Shift" }
# regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[bell]
animation = "Linear"
duration = 20

  [bell.command]
  program = "paplay"
  args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false


